version: '3'

services:
  bookmark-homepage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Map host port to container port
    environment:
      - PORT=3001    # Can be modified to change the application port
    volumes:
      - bookmark-data:/app/server/data  # Persist bookmark data
    restart: unless-stopped  # Restart policy

volumes:
  bookmark-data:  # Named volume for data persistence
